# Generated by Django 2.0.2 on 2018-07-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('asistencia_hombres', models.IntegerField()),
                ('asistencia_mujeres', models.IntegerField()),
                ('asistencia_jovenes', models.IntegerField()),
                ('asistencia_adolecentes', models.IntegerField()),
                ('asistencia_niños', models.IntegerField()),
                ('dia', models.CharField(max_length=50)),
            ],
        ),
    ]
