# Generated by Django 2.0.2 on 2018-07-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_grupo', models.IntegerField()),
                ('fecha_visita', models.DateField()),
                ('lider', models.CharField(max_length=70)),
                ('supervisor', models.CharField(max_length=70)),
                ('hermanos_familiar', models.IntegerField()),
                ('discipulos_familiar', models.IntegerField()),
                ('amigos_familiar', models.IntegerField()),
                ('niños_cristianos', models.IntegerField()),
                ('niños_amigos', models.IntegerField()),
                ('conversiones_familiar', models.IntegerField()),
                ('conversiones_niños', models.IntegerField()),
                ('telefonica', models.IntegerField(blank=True, null=True)),
                ('electronica', models.IntegerField(blank=True, null=True)),
                ('personal', models.IntegerField(blank=True, null=True)),
                ('esc_capacitacion', models.IntegerField(blank=True, null=True)),
                ('ofrenda_grupo', models.IntegerField(blank=True, null=True)),
                ('hermanos_iglesia', models.IntegerField()),
                ('discipulos_iglesia', models.IntegerField()),
                ('amigos_iglesia', models.IntegerField()),
                ('niños_iglesia', models.IntegerField()),
                ('conversiones_iglesia', models.IntegerField()),
                ('nuevos_convertidos', models.TextField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('faltaron_grupo_uno', models.CharField(blank=True, max_length=30)),
                ('faltaron_grupo_dos', models.CharField(blank=True, max_length=30)),
                ('faltaron_grupo_tres', models.CharField(blank=True, max_length=30)),
                ('faltaron_grupo_cuatro', models.CharField(blank=True, max_length=30)),
                ('faltaron_grupo_cinco', models.CharField(blank=True, max_length=30)),
                ('motivo_grupo_uno', models.CharField(blank=True, max_length=25)),
                ('motivo_grupo_dos', models.CharField(blank=True, max_length=25)),
                ('motivo_grupo_tres', models.CharField(blank=True, max_length=25)),
                ('motivo_grupo_cuatro', models.CharField(blank=True, max_length=25)),
                ('motivo_grupo_cinco', models.CharField(blank=True, max_length=25)),
                ('visito_despues_uno', models.CharField(blank=True, max_length=20)),
                ('visito_despues_dos', models.CharField(blank=True, max_length=20)),
                ('visito_despues_tres', models.CharField(blank=True, max_length=20)),
                ('visito_despues_cuatro', models.CharField(blank=True, max_length=20)),
                ('visito_despues_cinco', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
