# Generated by Django 2.0.2 on 2018-07-31 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conyuge_hijos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('nombres_familiar', models.CharField(max_length=50)),
                ('apellidos_familiar', models.CharField(max_length=50)),
                ('edad_familiar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('estado_civil', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('barrio', models.CharField(max_length=50)),
                ('fecha_conversion', models.DateField()),
                ('lugar_conversion', models.CharField(max_length=50)),
                ('iglesia_conversion', models.CharField(max_length=50)),
                ('pastor_conversion', models.CharField(max_length=50)),
                ('fecha_bautismo', models.DateField()),
                ('lugar_bautismo', models.CharField(max_length=50)),
                ('iglesia_bautismo', models.CharField(max_length=50)),
                ('pastor_bautismo', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='conyuge_hijos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
