# -*- encoding:utf-8 -*-
from django import forms

from apps.grupos.models import Grupos

class GruposForm(forms.ModelForm):

	class Meta:
		model = Grupos

		fields = [
			'nro_grupo',
			'fecha_visita',
			'lider',
			'supervisor',
			'hermanos_familiar',
			'discipulos_familiar',
			'amigos_familiar',
			'niños_cristianos',
			'niños_amigos',
			'conversiones_familiar',
			'conversiones_niños',
			'telefonica',
			'electronica',
			'personal',
			'esc_capacitacion',
			'ofrenda_grupo',
			'hermanos_iglesia',
			'discipulos_iglesia',
			'amigos_iglesia',
			'niños_iglesia',
			'conversiones_iglesia',
			'nuevos_convertidos',
			'comentarios',
			'faltaron_grupo_uno',
			'faltaron_grupo_dos',
			'faltaron_grupo_tres',
			'faltaron_grupo_cuatro',
			'faltaron_grupo_cinco',
			'motivo_grupo_uno',
			'motivo_grupo_dos',
			'motivo_grupo_tres',
			'motivo_grupo_cuatro',
			'motivo_grupo_cinco',
			'visito_despues_uno',
			'visito_despues_dos',
			'visito_despues_tres',
			'visito_despues_cuatro',
			'visito_despues_cinco',
		]
		labels = {
			'nro_grupo': 'Número grupo',
			'fecha_visita': 'Fecha de visita',
			'lider': 'Lider del grupo',
			'supervisor': 'Supervisor',
			'hermanos_familiar': 'Hermanos',
			'discipulos_familiar': 'Discipulos',
			'amigos_familiar': 'Amigos',
			'niños_cristianos': 'Niños Cristianos',
			'niños_amigos': 'Niños Amigos',
			'conversiones_familiar': 'Conversiones',
			'conversiones_niños': 'Conversiones niños',
			'telefonica': 'Telefónica',
			'electronica': 'Electrónica',
			'personal': 'Personal',
			'esc_capacitacion': 'Esc. de capacitación',
			'ofrenda_grupo': 'Ofrenda del grupo',
			'hermanos_iglesia': 'Hermanos',
			'discipulos_iglesia': 'Discipulos',
			'amigos_iglesia': 'Amigos',
			'niños_iglesia': 'Niños',
			'conversiones_iglesia':'Conversiones',
			'nuevos_convertidos': 'Nuevos convertidos',
			'comentarios': 'Comentarios',
			'faltaron_grupo_uno': 'Faltaron al grupo #1',
			'faltaron_grupo_dos': 'Faltaron al grupo #2',
			'faltaron_grupo_tres': 'Faltaron al grupo #3',
			'faltaron_grupo_cuatro': 'Faltaron al grupo #4',
			'faltaron_grupo_cinco': 'Faltaron al grupo #5',
			'motivo_grupo_uno': 'Motivo - Persona #1',
			'motivo_grupo_dos': 'Motivo - Persona #2',
			'motivo_grupo_tres': 'Motivo - Persona #3',
			'motivo_grupo_cuatro': 'Motivo - Persona #4',
			'motivo_grupo_cinco': 'Motivo - Persona #5',
			'visito_despues_uno': 'Visitó después del grupo #1',
			'visito_despues_dos': 'Visitó después del grupo #2',
			'visito_despues_tres': 'Visitó después del grupo #3',
			'visito_despues_cuatro': 'Visitó después del grupo #4',
			'visito_despues_cinco':'Visitó después del grupo #5',
		}
		widgets = {
			'nro_grupo': forms.TextInput(attrs={'class':'form-control'}),
			'fecha_visita': forms.TextInput(attrs={'class':'form-control'}),
			'lider': forms.TextInput(attrs={'class':'form-control'}),
			'supervisor': forms.TextInput(attrs={'class':'form-control'}),
			'hermanos_familiar': forms.TextInput(attrs={'class':'form-control'}),
			'discipulos_familiar': forms.TextInput(attrs={'class':'form-control'}),
			'amigos_familiar': forms.TextInput(attrs={'class':'form-control'}),
			'niños_cristianos': forms.TextInput(attrs={'class':'form-control'}),
			'niños_amigos': forms.TextInput(attrs={'class':'form-control'}),
			'conversiones_familiar': forms.TextInput(attrs={'class':'form-control'}),
			'conversiones_niños': forms.TextInput(attrs={'class':'form-control'}),
			'telefonica': forms.TextInput(attrs={'class':'form-control'}),
			'electronica': forms.TextInput(attrs={'class':'form-control'}),
			'personal': forms.TextInput(attrs={'class':'form-control'}),
			'esc_capacitacion': forms.TextInput(attrs={'class':'form-control'}),
			'ofrenda_grupo': forms.TextInput(attrs={'class':'form-control'}),
			'hermanos_iglesia': forms.TextInput(attrs={'class':'form-control'}),
			'discipulos_iglesia': forms.TextInput(attrs={'class':'form-control'}),
			'amigos_iglesia': forms.TextInput(attrs={'class':'form-control'}),
			'niños_iglesia': forms.TextInput(attrs={'class':'form-control'}),
			'conversiones_iglesia':forms.TextInput(attrs={'class':'form-control'}),
			'nuevos_convertidos': forms.Textarea(attrs={'class':'form-control'}),
			'comentarios': forms.Textarea(attrs={'class':'form-control'}),
			'faltaron_grupo_uno': forms.TextInput(attrs={'class':'form-control'}),
			'faltaron_grupo_dos': forms.TextInput(attrs={'class':'form-control'}),
			'faltaron_grupo_tres': forms.TextInput(attrs={'class':'form-control'}),
			'faltaron_grupo_cuatro': forms.TextInput(attrs={'class':'form-control'}),
			'faltaron_grupo_cinco': forms.TextInput(attrs={'class':'form-control'}),
			'motivo_grupo_uno': forms.TextInput(attrs={'class':'form-control'}),
			'motivo_grupo_dos': forms.TextInput(attrs={'class':'form-control'}),
			'motivo_grupo_tres': forms.TextInput(attrs={'class':'form-control'}),
			'motivo_grupo_cuatro': forms.TextInput(attrs={'class':'form-control'}),
			'motivo_grupo_cinco': forms.TextInput(attrs={'class':'form-control'}),
			'visito_despues_uno': forms.TextInput(attrs={'class':'form-control'}),
			'visito_despues_dos': forms.TextInput(attrs={'class':'form-control'}),
			'visito_despues_tres': forms.TextInput(attrs={'class':'form-control'}),
			'visito_despues_cuatro': forms.TextInput(attrs={'class':'form-control'}),
			'visito_despues_cinco':forms.TextInput(attrs={'class':'form-control'}),
		}