from django.db import models

# Create your models here.
class Grupos(models.Model):
	nro_grupo = models.IntegerField()
	fecha_visita = models.DateField()
	lider = models.CharField(max_length=70)
	supervisor = models.CharField(max_length=70)
	hermanos_familiar = models.IntegerField()
	discipulos_familiar = models.IntegerField()
	amigos_familiar = models.IntegerField()
	niños_cristianos = models.IntegerField()
	niños_amigos = models.IntegerField()
	conversiones_familiar = models.IntegerField()
	conversiones_niños = models.IntegerField()
	telefonica = models.IntegerField(null=True, blank=True)
	electronica = models.IntegerField(null=True, blank=True)
	personal = models.IntegerField(null=True, blank=True)
	esc_capacitacion = models.IntegerField(null=True, blank=True)
	ofrenda_grupo = models.IntegerField(null=True, blank=True)
	hermanos_iglesia = models.IntegerField()
	discipulos_iglesia = models.IntegerField()
	amigos_iglesia = models.IntegerField()
	niños_iglesia = models.IntegerField()
	conversiones_iglesia = models.IntegerField()
	nuevos_convertidos = models.TextField(null=True, blank=True)
	comentarios = models.TextField(null=True, blank=True)
	faltaron_grupo_uno = models.CharField(max_length=30, blank=True)
	faltaron_grupo_dos = models.CharField(max_length=30, blank=True)
	faltaron_grupo_tres = models.CharField(max_length=30, blank=True)
	faltaron_grupo_cuatro = models.CharField(max_length=30, blank=True)
	faltaron_grupo_cinco = models.CharField(max_length=30, blank=True)
	motivo_grupo_uno = models.CharField(max_length=25, blank=True)
	motivo_grupo_dos = models.CharField(max_length=25, blank=True)
	motivo_grupo_tres = models.CharField(max_length=25, blank=True)
	motivo_grupo_cuatro = models.CharField(max_length=25, blank=True)
	motivo_grupo_cinco = models.CharField(max_length=25, blank=True)
	visito_despues_uno = models.CharField(max_length=20, blank=True)
	visito_despues_dos = models.CharField(max_length=20, blank=True)
	visito_despues_tres = models.CharField(max_length=20, blank=True)
	visito_despues_cuatro = models.CharField(max_length=20, blank=True)
	visito_despues_cinco = models.CharField(max_length=20, blank=True)